### ISSUE TITLE
Splat crashing LSP.

### ISSUE THREAD

**Issue by MaxBeaud** [c3lang/tree-sitter-c3#22]
While the following is valid C3 it make the LSP and highlighting crash.
`Rectangle pos = {...frameRec, ...spriteSize};`
Where Rectangle is something like `struct Rectangle { x, y, h, w };` (pseudo code).

**Comment by pherrymason** [comment]
This is an error of the LSP, not treesitter's C3 grammar. 
Could you report this there? https://github.com/pherrymason/c3-lsp/issues

Thanks!

**Comment by cbuttner** [comment]
It was actually missing from the grammar. Fixed now!

**Comment by MaxBeaud** [comment]
Perhaps this is a Helix issue but I am on the main branch and splatting still crashes tree-sitter.
![Image](https://github.com/user-attachments/assets/d9aa3df0-e9bf-484d-9d95-635af32e325c)
mind you this does not happen on VsCode.

**Comment by cbuttner** [comment]
@MaxBeaud I can't reproduce. You can test it here: https://c3lang.github.io/tree-sitter-c3/

**Comment by MaxBeaud** [comment]
@cbuttner The issue was targeting the main branch in the `language.toml` file and helix not pulling and building the latest. Using the latest commit hash, there are no issues anymore.
